[tool.poetry]
name = "agl_anonymizer_pipeline"
version = "0.1.4"
description = "This package is made to censor sensitive data in images and extract the contents. NER is planned for the future"
authors = ["maxhild <58726316+maxhild@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
requests = "2.31.0"
flair = "0.13.0"
gender-guesser = "0.4.0"
gensim = "^4.1.2"
##
PyPDF = "^5.0"
reportlab = "4.1.0"
pytesseract = "^0.3.9"
opencv-python-headless = "^4.10.0.84"
transformers = "^4.20.0"
spacy = "^3.4.0"
Pillow = "^9.0.0"
torch = "^2.4.1"
torchvision = "^0.19.1"
torchaudio = "^2.4.1"


